- name: Instalando OpenJDK
  package:
    name: java-1.8.0-openjdk-devel
    state: present
- shell: "echo 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64' >> ~/.bash_profile"
- shell: "echo 'export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4.x86_64/jre' >> ~/.bash_profile"
- shell: "source ~/.bash_profile"