- name: Obtener IP de los esclavos
  hosts: meta-instancia_workers
  become: true
  roles:
    - docker-slaves-ip

- name: Crear archivo de ip
  hosts: meta-instancia_manager
  become: true
  roles:
    - docker-slaves-ip-file
