---
- name: Creación de usuario Windows
  hosts: all
  gather_facts: False
  vars_files:
    - vars_conexion_win.yml
  tasks:
    - name: Ensure user bob is present
      win_user:
        name: jsegura
        password: Tsoft*2017
        state: present
        groups:
          - Administrators
