- name: Cambio de Password Instancia Openstack 
  hosts: all
  tasks:
    - name: Descomentar PermitRootLogin
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        insertafter: "^#PermitRootLogin yes"
        line: "PermitRootLogin yes"
    
    - name: recarga el servicio sshd
      command: service sshd reload
      
    - name: Crea Password Usuario linux
      shell: "printf 'Ts0ft*201919\nTs0ft*201919\n' | passwd root"
      