- name: Creando una VM en Azure componentes por defecto
  hosts: all
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        #auth_source: cli
        #auth_source: auto
        subscription_id: ac46bd0e-db91-4d3a-b02b-48c218bf7efb
        client_id: 5e3634e0-6d9c-40b6-b261-bfb64105ea68
        secret: E.n5plSH9_]sBUH.0GMYyrwLwlVAY4]p
        tenant: 024e2589-9812-4d22-bae5-edb9856aa2cf
        resource_group: "{{ resource_group }}"
        admin_username: "{{ user_vm }}"
        admin_password: "{{ pass_vm }}"
        name: "{{ vm_name }}"
        vm_size: "{{ flavor }}"
        managed_disk_type: Standard_LRS
        open_ports: 8443
        network_interface_names: nebula-vnet
        image: OpenLogic:CentOS:7.5:latest
      loop: "{{ vm_name_list }}"
      loop_control:
        loop_var: vm_name
      delegate_to: localhost


      #hola