- name: Creando una VM en Azure componentes por defecto
  hosts: all
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        auth_source: cli
        resource_group: "{{ resource_group }}"
        admin_username: "{{ user_vm }}"
        admin_password: "{{ pass_vm }}"
        name: "{{ vm_name }}"
        vm_size: "{{ flavor }}"
        managed_disk_type: Standard_LRS
        open_ports: 8443
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.6'
          version: latest
      loop: "{{ vm_name_list }}"
      loop_control:
        loop_var: vm_name
      environment:
        ANSIBLE_KEEP_REMOTE_FILES: True