- name: Creando una VM en Azure componentes por defecto
  hosts: all
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        auth_source: cli
        resource_group: "{{ resource_group }}"
        admin_username: "{{ user_vm }}"
        admin_password: "{{ pass_vm }}"
        name: "{{ vm_name }}"
        vm_size: "{{ flavor }}"
        managed_disk_type: Standard_LRS
        open_ports: 8443
        network_interface_names: nebula-vnet
        image: OpenLogic:CentOS:7.5:latest
      loop: "{{ vm_name_list }}"
      loop_control:
        loop_var: vm_name
      delegate_to: localhost