- name: Creando una VM en Azure componente por defecto
  hosts: all
  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        auth_source: cli
        resource_group: test-nebula
        name: "{{ vm_name }}"
        admin_username: nebula
        admin_password: Ts0ft*201919
        vm_size: Standard_D2s_v3
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.6'
          version: latest