- name: Creando una VM en Azure componente por defecto
  hosts: all
  tasks:
    - name: Remove a VM and all resources that were autocreated
      azure_rm_virtualmachine:
        resource_group: test-nebula
        name: "{{ vm_name }}"
        remove_on_absent: all_autocreated
        state: absent