- hosts: all
  become: yes
  roles:
    - app/java-install
    - firewall-turnoff
  tasks:
    ################################ (Instalacion JIRA) ##################################
    - name: Crear carpeta para instaladores Jira
      file:
        path: /opt/jirasoftware
        state: directory
    - name: Crea Usuario Jira
      user:
        name: jira
        state: present
    - name: Remover Password Usuario Jira
      command: passwd -d jira
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /tmp/atlassian-jira-software-8.0.0.tar.gz
        dest: /opt/jirasoftware
        remote_src: yes
    - name: Permisos para carpeta de instaladores
      file:
        path: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /home/jirasoftware-home/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crea y exporta Variable JIRA_HOME
      shell: export JIRA_HOME=/home/jirasoftware-home
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile-b-jira.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: Agrega export JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export JIRA_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$JIRA_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: Copiar archivo para start de servicio jira
      copy:
        src: /tmp/jira
        dest: /etc/init.d/
        remote_src: yes
        mode: +x
    - name: Habilitar servicio jira
      shell: /sbin/chkconfig --add jira
      become: yes
    - name: creacion de archivo jira.service
      lineinfile:
        path: /usr/lib/systemd/system/jira.service
        line: "[Unit]\n
              Description=JIRA Service\n
              After=network.target iptables.service firewalld.service firewalld.service httpd.service\n
              \n
              [Service]\n
              Type=forking\n
              User=jira\n
              Environment=JAVA_HOME=/usr/java/jdk-java\n
              Environment=JIRA_HOME=/home/jirasoftware-home\n
              ExecStart=/opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh\n
              ExecStop=/opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/stop-jira.sh\n
              \n
              [Install]\n
              \n
              WantedBy=multi-user.target"
        create: yes
    - name: systemctl 1
      become: yes
      shell: systemctl daemon-reload
    - name: systemctl 2
      become: yes
      shell: systemctl start jira
    