- name: Ejecutar comando en Windows
  gather_facts: yes
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Comand inside
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig
