---
- name: Creación de usuario Linux
  hosts: localhost
  tasks:
    - name: Install aplications for create pass encrypte
      shell: sudo apt-get install -y whois
    - name: Creations encrypte password
      command: mkpasswd --method=sha-512
      register: pass
    - name: Create a login user with {{ pass.stdout }}
      user:
        name: NewUser
        password: "{{ pass.stdout }}"
        system: yes
        groups: sudo
        state: present
