---
- name: Instalacion de servidor Apache
  hosts: all
  tasks:
    - name: Install Package
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Install Package
      apt: 
        name: httpd 
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
