---
- name: Instalacion de servidor Apache
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Install Package
      become: yes
      yum:
        name: httpd
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    - name: Install Package
      become: yes
      apt:
        name: httpd
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
