
- name: Enviar email
  hosts: all
  tasks:
    - mail:
        host: 10.10.20.103
        port: 25
        to: Janina Segura <"{{ owner_email }}">
        subject: Ansible-report
        body: 'Tu servidor {{ ansible_hostname }} ha sido aprovisionado satisfactoriamente.'