
- name: Enviar email
  hosts: all
  tasks:
    - mail:
        host: 10.10.20.103
        port: 25
        username: tsoft\jhon.catro
        password: Tsoft2018
        to: Janina Segura <janina.segura@tsoftlatam.com>
        subject: Ansible-report
        body: 'Tu servidor {{ ansible_hostname }} ha sido aprovisionado satisfactoriamente.'