- name: Ejecución de Terraform
  hosts: all
  gather_facts: false
  tasks:
      - terraform:
            project_path: /etc/terraform/telefonica/jmiter
            state: present
            #variables_file: /etc/terraform/telefonica/jmiter/variable.tfvars
            variables:
                  region: sa-chile-1
                  vm_name: jmeter_server
        become: yes
        become_user: ansibleadmin
        become_method: enable
