- name: Ejecución de Terraform
  hosts: all
  gather_facts: true
  tasks:
      - terraform:
            project_path: /etc/terraform/telefonica/jmiter
            state: present
        become: yes
        become_user: ansibleadmin
        become_method: sudo
