- name: Ejecución de Terraform
  hosts: all
  gather_facts: true
  tasks:
      - terraform:
            project_path: /etc/terraform/telefonica/jmiter
            state: present
            variables:
                  region: sa-chile-1
        become: yes
        become_user: su
        become_method: sudo
