- name: Ejecución de Terraform
  hosts: all
  gather_facts: true
  become: yes
  become_user: ansibleadmin
  become_method: sudo
  tasks:
      - terraform:
            project_path: /etc/terraform/telefonica/jmiter
            state: present
