- name: Loop
  hosts: all
  become: yes
  tasks:
    - name: mensaje en consola
      shell: "wall hola mundo {{ item }} $(date)"
      loop: [1,2,3,4,5,6,7,8,9]
      loop_control:
        loop_var: "async_item"
      register: async_results
    - debug: var=async_results