- name: Traer archivo desde una vm
  hosts: jhon
  tasks:
    - fetch: 
        src: "{{ path_source }}{{ name_file }}"
        dest: /tmp/
        flat: yes
- name: Traer archivo desde una vm
  hosts: "{{ ansible_limit }}"
  tasks:
    - name: Copy 2 a otra vm no funciona
      copy:
        src: /tmp/"{{ name_file }}"
        dest: "{{ path_dest }}"