- name: Tranferir archivos
  hosts: all
  tasks:
    # - name: Traer archivo desde una vm
    #   fetch: 
    #     src: /home/hola.txt
    #     dest: /tmp/
    #     flat: yes
    - name: Copy 2 a otra vm no funciona {{ansible_limit}}
      copy:
        src: /tmp/hola.txt
        dest: /tmp/
        remote_src: yes 
      delegate_to: localhost
