---
- name: Traer archivo desde una vm
  hosts: all
  vars:
  tasks:
    - fetch: 
        src: "{{ path_source }}{{ name_file }}"
        dest: /tmp/
        flat: yes   
- name: Pegar archivo en una vm
  hosts: all:!jhon
  tasks:
    - copy:
        src: /tmp/"{{ name_file }}"
        dest: "{{ path_dest }}"
