- name: tranferir archivo
  hosts: all
  gather_facts: yes
  tasks:
    # - name: get_url con un servidor ftp
    #   get_url:
    #     url: file:///home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/credentials.csv
    #   delegate_to: localhost
    # - name: Con synchronize rsync debe estar instalado en ambos servidores (RHEL no lo tiene por defecto)
    #   synchronize:
    #     src: /home/ansibleadmin/jira
    #     dest: /tmp
    # - name: copy en la misma vm
    #   become: yes
    #   become_user: root
    #   copy:
    #     src: /tmp/jdk-8u201-linux-x64.tar.gz
    #     dest: /root
    #     remote_src: yes
    #     mode: 0664
    # - name: Copy 2 a otra vm no funciona
    #   copy:
    #     dest: /temp
    #     src: /home/ansibleadmin/jira/jira
    #     remote_src: no
    #     mode: 0644
    #   delegate_to: localhost
    #   become_user: ansibleadmin
    #   become: yes
    - name: Transferir un archivo por scp
      #shell: scp /home/ansibleadmin/jira/jira root@10.41.101.206:/tmp
      shell: |
        set timeout 300
        scp /home/ansibleadmin/jira/jira root@10.41.101.206:/tmp

        expect "root@10.41.101.206's password:"
        send "root"
      args:
        executable: /usr/bin/expect
