- name: tranferir archivo
  hosts: jhon
  gather_facts: yes
  tasks:
    # - name: get_url con un servidor ftp
    #   get_url:
    #     url: file:///home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/credentials.csv
    #   delegate_to: localhost
    # - name: Con synchronize rsync debe estar instalado en ambos servidores (RHEL no lo tiene por defecto)
    #   synchronize:
    #     src: /home/ansibleadmin/jira
    #     dest: /tmp
    - name: copy
      copy:
        src: /home/ansibleadmin/jiracredentials.csv
        dest: /tmp/credentials.csv
