- name: tranferir archivo
  hosts: jhon
  gather_facts: yes
  tasks:
    # - name: get_url con un servidor ftp
    #   get_url:
    #     url: file:///home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/credentials.csv
    #   delegate_to: localhost
    # - name: Con synchronize rsync debe estar instalado en ambos servidores (RHEL no lo tiene por defecto)
    #   synchronize:
    #     src: /home/ansibleadmin/jira
    #     dest: /tmp
    - name: copy
      become: yes
      become_user: root
      copy:
        #src: /home/ansibleadmin/jira/credentials.csv
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: ansibleadmin@10.41.101.198:/root
        remote_src: yes
        mode: 0664
      ignore_errors: yes
    # # transfer local pub-key to remote authorized_keys
    # - name: fetch local ssh key from root user
    #   shell: cat /root/.ssh/id_rsa.pub
    #   register: ssh_keys
    #   changed_when: false
    # - name: deploy ssh key to remote server
    #   authorized_key:
    #     user: "root"
    #     key: "{{ item }}"
    #   delegate_to: "server-b"
    #   with_items:
    #     - "{{ ssh_keys.stdout }}"
    # # fetch remote host key and add to local known_hosts
    # # to omit key accept prompt
    # - name: fetch ssh rsa host key from remote server
    #   shell: cat /etc/ssh/ssh_host_rsa_key.pub
    #   register: ssh_host_rsa_key
    #   delegate_to: server-b
    #   changed_when: false
    # - name: create /root/.ssh/ if not existant
    #   file:
    #     path: "/root/.ssh/"
    #     owner: root
    #     group: root
    #     mode: 0700
    #     state: directory
    # - name: add hostkey to root known host file
    #   lineinfile:
    #     path: "/root/.ssh/known_hosts"
    #     line: "{{ server-b.inventory_hostname }} {{ ssh_host_rsa_key.stdout }}"
    #     mode: 0600
