# - name: Crear manager del cluster
#   shell: docker swarm init
- name: Obtener token para worker
  shell: docker swarm join-token -q worker
  register: worker_token
- name: Agregar worker al cluster
  shell: "docker swarm join --token {{ worker_token.stdout }} {{hostvars['8622477f-0c69-4b92-b306-4b71a7a65600']['ansible_eth0']['ipv4']['address']}}:2377"