- name: Instalacion de Bitbucket
  hosts: all
  become: yes
  tasks:
    ########## Instalaci贸n Java ############
    - name: Descargar archivo de instalaci贸n JDK
      get_url:
        url: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
        dest: /tmp/
        mode: a+x
      ignore_errors: yes
    - name: Crea Carpeta JAVA
      file: 
        path: /usr/java
        state: directory
    - name: Descomprime Archivo
      unarchive:
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: /usr/java
        remote_src: yes
    - name: Renombra carpeta java
      command: mv /usr/java/jdk1.8.0_201 /usr/java/jdk-java
    - name: Crea y exportar Variable JAVA
      shell: export JAVA_HOME=/usr/java/jdk-java
    - name: Crea y exporta Variable PATH
      shell: export PATH=$JAVA_HOME/bin:$PATH
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile-b-java.bkp
    - name: Agrega JAVA_HOME y PATH al archivo Profile
      shell: sed -i '$a JAVA_HOME=/usr/java/jdk-java' /etc/profile; sed -i '$a export JAVA_HOME' /etc/profile; sed -i '$a PATH=$JAVA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JAVA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME=/usr/java/jdk-java"
        create: yes
    # ########## Instalaci贸n Bitbucket ############
    - name: Crea Usuario Bamboo
      user:
        name: bamboo
        state: present
    - name: Remover Password Usuario Bamboo
      command: passwd -d bamboo
    - name: Descargar bin y darle permiso de ejecuci贸n
      get_url:
        url: https://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-6.8.1.tar.gz
        dest: /tmp/
        mode: a+x
      ignore_errors: yes
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /tmp/atlassian-bamboo-6.8.1.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /opt/atlassian/bamboo/
        state: directory
        owner: bamboo
        group: bamboo
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Agrega bamboo.home
      lineinfile:
        path: /opt/atlassian/bamboo/atlassian-bamboo-6.8.1/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties
        line: "bamboo.home=/home/bamboo"
        create: yes

    - name: Crea y exporta Variable BAMBOO_HOME
      shell: export BAMBOO_HOME=/home/bamboo
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega BAMBOO_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "BAMBOO_HOME=/home/bamboo"
        create: yes
    - name: Agrega export BAMBOO_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export BAMBOO_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$BAMBOO_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega BAMBOO_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "BAMBOO_HOME=/home/bamboo"
        create: yes
    - name: Start Bamboo
      shell: service bamboo start

    - name: Desactivar SELinux
      command: setenforce 0
    - name: Deshabilitar SELinux
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX=' 
        line: 'SELINUX=disabled'
    - name: firewall rhel7
      command: systemctl stop firewalld