- name: Guest Creation
  gather_facts: no
  vars_files:
    - ../vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "RHEL68-for-jboss"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        networks:
          - name: "{{ network }}"
        #     ip: 10.41.101.235
        #     netmask: 255.255.255.0
        #     gateway: 10.41.101.1
        cluster: "{{ cluster }}"
        customization:
          dns_servers: "{{ dns_server }}"
        wait_for_ip_address: yes
      register: vm_result
