- name: VM Creation from Template
  gather_facts: no
  vars_files:
    - ../vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }}
      vmware_guest:
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        networks:
          - name: "{{ network }}"
        #     type: dhcp
        #     netmask: 255.255.255.0
        #     gateway: 10.41.101.1
        # customization:
        #   dns_servers: "{{ dns_server }}"
        wait_for_ip_address: yes
      register: vm_result
    - debug: var=vm_result
