- name: Instalación de Java y Jboss
  hosts: all
  gather_facts: yes
  become: yes
  user: root
  tasks:
    - name: Instalación de Java
      include_tasks: java-local-installations.yml
    - name: Instalación de Jboss
      include_tasks: jboss-local-installations.yml
