- name: Stop Jboss
  hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - ../vcenter_vars.yml
  vars:
    vm_name: "{{ ansible_limit }}"
  tasks:
    - name: Iniciando Servicio JBOSS
      at:
        command: sh /home/jboss/jboss-6.4/bin/jboss-cli.sh --connect command=:shutdown
        count: 1
        units: minutes
      environment:
        JAVA_HOME: /usr/java/jre-java
        JAVA_OPTS: -server -XX:+UseCompressedOops -verbose:gc -Xloggc:"/home/jboss/jboss-6.4/standalone/log/gc.log" -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=3M -XX:-TraceClassUnloading -Xms1303m -Xmx1303m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.modules.policy-permissions=true
    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
      register: vm_factss
      delegate_to: localhost
    - name: Set powerstate of a virtual machine to poweron u poweroff by using UUID (change the state module)
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        uuid: "{{ vm_factss.instance.hw_product_uuid }}"
        state: poweredoff
      delegate_to: localhost