- name: selinux
  command: setenforce 0
- name: Deshabilitar SELinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
- name: Stop service httpd, if started
  service:
    name: firewalld
    state: stopped
- name: firewall
  service: 
    name: firewalld
    enabled: no 
