- name: Crear carpeta de utilidades
  file: 
    path: /home/{{ ansible_ssh_user }}/performance/utils 
    state: directory 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para ejecutar pruebas
  template: 
    src: runTest.sh.j2 
    dest: /home/{{ ansible_ssh_user }}/performance/utils/runTest.sh 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para obtener log de la prueba
  copy: 
    src: getResults.sh 
    dest: /home/{{ ansible_ssh_user }}/performance/utils 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para regenerar el master
  copy: 
    src: regenerateMaster.sh 
    dest: /home/{{ ansible_ssh_user }}/performance/utils 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para regenerar los esclavos
  copy: 
    src: regenerateSlaves.sh 
    dest: /home/{{ ansible_ssh_user }}/performance/utils 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para reiniciar el stack
  template: 
    src: resetStack.sh.j2 
    dest: /home/{{ ansible_ssh_user }}/performance/utils/resetStack.sh 
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
