- name: Instalacion de GoCD
  hosts: all
  become: yes
  roles:
    - app/openjdk-install
  tasks:
    - name: Crea Usuario go
      user:
        name: go
        state: present
    - name: Remover Password Usuario go
      command: passwd -d go
    - name: Repositorio go-server
      yum_repository:
        name: go-server
        description: Go Server YUM repo
        baseurl: https://download.gocd.org/gocd.repo -o /etc/yum.repos.d/gocd.repo
        
      when: ansible_facts['os_family'] == "RedHat"
    - name: Instalación de GoCD Server
      package: 
        name: go-server
        state: present
    - name: Start de Servicio go-server
      command: systemctl start go-server
    - name: Habilitar de Servicio go-server
      command: systemctl enable go-server
    - name: Creanado directorio de artefactos
      file:
        path: /opt/artifacts
        state: directory
        owner: go
        group: go
        mode: u=rwx,go-rwx
        recurse: yes
