- name: Deploy VM from existing template {{ template_name }}
  gather_facts: no
  vars_files:
    - vcenter_variables.yml
  hosts: localhost
  tasks:
    - name: Clone a virtual machine {{ vm_name }} from existing template {{ template_name }} customize
      vmware_guest:
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        disk:
          - datastore: "{{ datastore }}"
            size_gb: 40
            type: thin
        hardware:
          hotadd_memory: True
          memory_mb: "{{memory_mb}}"
          hotadd_cpu: True
          num_cpus: "{{ num_cpus }}"
          num_cpu_cores_per_socket: "{{ num_cpu_cores_per_socket }}"
          networks:
            - name: "{{ network }}"
              # ip: "{{ ip_asigned }}"
              # netmask: "{{ mask_asigned }}"
        cluster: "{{ cluster }}"
        wait_for_ip_address: yes
      register: vm_result
