- name: Prueba 4 Obtener datos cambiar nombre y encontrar carpeta
  gather_facts: False
  vars_files:
    - vcenter_variables.yml
  hosts: localhost
  tasks:
    - name: "Find folder for VM - {{ vm_name }}"
      vmware_guest_find:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        name: "{{ vm_name }}"
      delegate_to: localhost
      register: vm_facts
