- name: Prueba 4 Obtener datos
  gather_facts: False
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - name: Get VM {{ vm_name }}'s IP
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        name: "{{ vm_name }}"
        schema: "vsphere"
      register: vm_facts
    - debug:
        var: vm_facts
        verbosity: 2
