- name: Encontrat path de carpeta de exixtencia de VM
  hosts: localhost
  remote_user: root
  become: true
  gather_facts: False
  vars_files:
    - vcenter_vars.yml
  #vars:
  #  ansible_pyhton_interpreter: "/usr/bin/env python3"
  tasks:
    - set_fact:
        vm_name: "Ansible-Probe"

    - name:
      vmware_guest_find:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        name: "{{ vm_name }}"
      delegate_to: localhost
      register: vm_facts
