- name: Remover una VM de VMware
  hosts: localhost
  gather_facts: False
  vars_files:
    - vcenter_variables.yml
  tasks:
    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
      register: vm_factss
    - name: Set powerstate of a virtual machine to poweroff by using UUID (change the state module)
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        uuid: "{{ vm_factss.instance.hw_product_uuid }}"
        state: poweredoff
      delegate_to: localhost
    - name: Remove a virtual machine by uuid
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        uuid: "{{ vm_factss.instance.hw_product_uuid }}"
        state: absent
      delegate_to: localhost
