- name: Prueba 4 Obtener datos cambiar nombre y encontrar carpeta
  gather_facts: False
  vars_files:
    - vcenter_variables.yml
  hosts: localhost
  tasks:
    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        folder: "{{ folder }}"
        name: "{{ vm_name }}"
      register: vm_facts
    - name: Rename "{{ vm_name }}" to "{{ new_vm_name }}" with "{{ vm_facts.instance.hw_product_uuid }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        cluster: "{{ cluster }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"
