- name: Instalación de VMware Tools
  hosts: "{{ vm_name }}"
  vars_files:
    - vcenter_variables.yml
  tasks:
    - name: Instalación de VMware Tools for Linux
      import_role:
        name: ruzickap.vmwaretools
      when: ansible_system == 'Linux'
    - name: Instalación de VMware Tools for Windows
      import_role:
        name: oatakan.windows_vmware_tools
      when: ansible_system == 'Windows'