- name: Instalacion de AWX
  hosts: all
  become: yes
  roles:
    - app/python-install
    - app/ansible-install
    - app/docker-install
    - app/git-install
    - app/nodejs-install
    - app/make-install
    - app/python-pip-install
    - app/docker-compose-install
  tasks:
    ########## Centos - Redhat #############
    - name: Descargar Proyecto AWX
      git:
        repo: https://github.com/ansible/awx.git
        dest: /root/awx
        clone: yes
    - name: Modificar dir PostgreSQL
      lineinfile:
        path: /root/awx/installer/inventory
        regexp: '^postgres_data_dir=/tmp/pgdocker' 
        line: postgres_data_dir=/var/lib/awx/pgdocker
    - name: Modificar dir Docker Compose
      lineinfile:
        path: /root/awx/installer/inventory
        regexp: '^docker_compose_dir=/tmp/awxcompose' 
        line: docker_compose_dir=/var/lib/awx
    - name: Instalcion de docker-py
      pip:
        name: docker-py
        state: present
    - name: Ejecutando Playbook de Instalación en Docker de AWX
      shell: ansible-playbook -i /root/awx/installer/inventory /root/awx/installer/install.yml