- name: Crear carpeta de utilidades
  file: path=/home/{{ hostvars['jhon-1']['ansible_ssh_user'] }}/performance/utils state=directory owner={{ hostvars['jhon-1']['ansible_ssh_user'] }} group={{ hostvars['jhon-1']['ansible_ssh_user'] }}

- name: Genrando archivo con direccion IP de los esclavos
  copy:
    content: "{% for host in groups.workers %}{% set first_loop = loop.index %}{% for result in hostvars[host]['ip']['results'] %}{% if first_loop == 1 and loop.index == 1 %}{{result.stdout}}{% else %},{{result.stdout}}{% endif %}{% endfor %}{% endfor %}"
    dest: /home/{{ hostvars['jhon-1']['ansible_ssh_user'] }}/performance/utils/ipAddressSlaves.csv
    owner: "{{ hostvars['jhon-1']['ansible_ssh_user'] }}"
    group: "{{ hostvars['jhon-1']['ansible_ssh_user'] }}"
