- name: Instalacion de Jenkins
  hosts: all
  become: yes
  roles:
    - java-install
  tasks:
    ######### Instalación Jenkins ############
    - name: Enable Jenkins Repository
      shell: curl --silent --location http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo | sudo tee /etc/yum.repos.d/jenkins.repo
    - name: Add the repository
      shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
    - name: Install Jenkins
      yum:
        name: jenkins
        state: latest
    - name: Start Service Jenkins
      service:
        name: jenkins
        state: started
    - name: 
      command: systemctl enable jenkins
    - name: Deshabilitar SELinux
      command: setenforce 0
    - name: firewall rhel7
      command: systemctl stop firewalld
    - name: Contraseña Inicial
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword