- hosts: all
  become: yes
  tasks:
    ################################ (Instalacion JAVA) ##################################
    - name: Crea Carpeta JAVA
      file: path=/usr/java state=directory
    - name: Descomprime Archivo
      unarchive:
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: /usr/java
        remote_src: yes
    - name: Renombra carpeta java
      command: mv /usr/java/jdk1.8.0_201 /usr/java/jdk-java
    - name: Crea y exportar Variable JAVA
      shell: export JAVA_HOME=/usr/java/jdk-java
    - name: Crea y exporta Variable PATH
      shell: export PATH=$JAVA_HOME/bin:$PATH
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile-b-java.bkp
    - name: Agrega JAVA_HOME archivo Profile
      shell: sed -i '$a JAVA_HOME=/usr/java/jdk-java' /etc/profile
    - name: Modifica Archivo PROFILE
      shell: sed -i '$a export JAVA_HOME' /etc/profile; sed -i '$a PATH=$JAVA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
