- hosts: all
  become: yes
  tasks:
    ###################################################################
    #Respaldo de Algunos Ejemplos
    #          - name: Create file
    #            file: path=/home/gabo/probe-ansible.txt state=touch
    #          - name: Copia Archivo
    #            copy:
    #                    src: /home/gabo/probe-ansible.txt
    #                    dest: /home/ansible.txt
    #                    remote_src: yes
    ###################################################################

    ################################ (Instalacion JAVA) ##################################
    - name: Crea Carpeta JAVA
      file: path=/usr/java state=directory
    - name: Descomprime Archivo
      unarchive:
        src: /root/jdk-11.0.2_linux-x64_bin.tar.gz
        dest: /usr/java
        remote_src: yes
    - name: Eliminar carperta
      command: rm -rf /usr/java/jdk-java
    - name: Renombra carpeta java
      command: mv /usr/java/jdk-11.0.2 /usr/java/jdk-java
    - name: Crea Variable JAVA
      shell: JAVA_HOME=/usr/java/jdk-java
    - name: Export JAVA_HOME
      shell: export JAVA_HOME
    - name: Crea Variable PATH
      shell: PATH=$JAVA_HOME/bin:$PATH
    - name: Export PATH
      shell: export PATH
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile.bkp
    - name: Agrega JAVA_HOME archivo Profile
      shell: sed -i '$a JAVA_HOME=/usr/java/jdk-java' /etc/profile
    - name: Modifica Archivo PROFILE
      shell: sed -i '$a export JAVA_HOME' /etc/profile; sed -i '$a PATH=$JAVA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
