- name: tranferir archivo
  hosts: all
  become: yes
  tasks:
    # - name: Crear carpeta para instaladores
    #   command: mkdir /tmp/jira/jirasoftware
    #   ignore_errors: yes
    # - name: Download file from a file path
    #   get_url:
    #     url: file:///home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/credentials.csv
    #   delegate_to: localhost
    #   ignore_errors: yes
    # - name: synchronize between nodes
    #   environment:
    #     RSYNC_PASSWORD: root
    #   synchronize:
    #     src: rsync://ansibleadmin@Ansible-Server:/home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/
    #     mode: pull
    #   delegate_to: localhost
    #   ignore_errors: yes
    # - name: Transfer file from ServerA to ServerB
    #   synchronize:
    #     src: /home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/
    #   delegate_to: Ansible
    #   ignore_errors: yes
    # - name: Descomprimiendo archivo de instalacion
    #   unarchive:
    #     src: /tmp/jira/atlassian-jira-software-8.0.1.tar.gz
    #     dest: /tmp/jira/jirasoftware
    #     remote_src: yes
    - name: Crea Usuario Jira
      command: useradd -d /home/jboss -s /bin/bash -m jira
    - name: Crea Password Usuario Jira
      command: echo 1234 | passwd jira --stdin
    - name: Usuario JBOSS Owner carpeta JBOSS
      command: chown -R jira:jira /tmp/jira/jirasoftware
    - name: Usuario JBOSS Owner carpeta JBOSS
      command: chmod -R u=rwx,go-rwx /tmp/jira/jirasoftware
