- name: Instalacion de Jira
  hosts: all
  tasks:
    - name: Crear carpeta para instaladores
      file:
        path: /opt/jirasoftware
        state: directory
    # - name: Tranferir archivo (tarea en desarrollo)
    - name: Crea Usuario Jira
      become: yes
      become_method: sudo
      become_user: root
      shell: /usr/sbin/useradd --create-home --comment "Account for running Jira Software" --shell /bin/bash jira
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /opt/atlassian-jira-software-8.0.0.tar.gz
        dest: /opt/jirasoftware
        remote_src: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /opt/jirasoftware/opt/jirasoftware/atlassian-jira-software-8.0.0-standalone
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    # - name: Usuario Jira Owner carpeta Jira
    #   shell: chown -R jira:jira /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone
    # - name: Usuario Jira Owner carpeta Jira
    #   shell: chmod -R u=rwx,go-rwx /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /home/jirasoftware-home
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    # - name: Crear carpeta home de Jira
    #   file: path=/home/jirasoftware-home state=directory
    # - name: Usuario Jira Owner carpeta Jira
    #   command: chown -R jira:jira /home/jirasoftware-home
    # - name: Usuario Jira Owner carpeta Jira
    #   command: chmod -R u=rwx,go-rwx /home/jirasoftware-home

    - name: Crea y exporta Variable JIRA_HOME
      shell: export JIRA_HOME=/home/jirasoftware-home
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile-b-jira.bkp
    - name: Agrega JIRA_HOME archivo Profile
      shell: sed -i '$a JIRA_HOME=/home/jirasoftware-home' /etc/profile
    - name: Modifica Archivo PROFILE
      shell: sed -i '$a export JIRA_HOME' /etc/profile; sed -i '$a PATH=$JIRA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      shell: sed -i '$a export JIRA_HOME=/home/jirasoftware-home' /etc/environment

    - name: Start Jira
      shell: sh /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh
      become: yes
      become_method: su
      become_user: jira
