- name:
  hosts: Ansible
  become_user: ansibleadmin
  become: yes
  tasks:
    - name: Copiar Archivo para Starting JIRA Automaticamente
      copy:
        dest: /etc/init.d/
        src: /home/ansibleadmin/jira/jira
        remote_src: no
        mode: 0751
      #delegate_to: Ansible
    # - name: Start Jira
    #   shell: sh /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh
    #   # - name: Iniciando Servicio Jira
    #   #   at:
    #   #     command: sh /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh
    #   #     count: 1
    #   #     units: minutes
    #   become: yes
    #   become_method: su
    #   become_user: jira
    #   environment:
    #     PATH: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin:/home/jirasoftware-home/bin:/usr/java/jdk-java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
    #     JAVA_HOME: /usr/java/jdk-java
    #     JIRA_HOME: /home/jirasoftware-home
