- name: Instalacion de Jira
  hosts: all
  tasks:
    - name: Crear carpeta para instaladores
      file:
        path: /opt/jirasoftware
        state: directory
    # - name: Tranferir archivo (tarea en desarrollo)
    - name: Crea Usuario Jira
      user:
        name: jira
        state: present

    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /opt/atlassian-jira-software-8.0.0.tar.gz
        dest: /opt/jirasoftware
        remote_src: yes
    - name: Permisos para carpeta de instaladores
      file:
        path: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /home/jirasoftware-home/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes

    - name: Crea y exporta Variable JIRA_HOME
      shell: export JIRA_HOME=/home/jirasoftware-home
    # - name: Respaldo Archivo Profile
    #   command: cp /etc/profile /etc/profile-b-jira.bkp
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile-b-jira.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: Agrega export JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export JIRA_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$JIRA_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: reboot
      reboot:
        reboot_timeout: 300
    # - name: Start Jira
    #   script: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh
    #   become: yes
    #   become_method: sudo
    #   become_user: jira
