- name: tranferir archivo
  hosts: all
  tasks:
    - name: Crear carpeta para instaladores
      command: mkdir /tmp/jira
      ignore_errors: yes
    - name: copy file at root dir of flash in slot 3 of sw1(ios)
      net_put:
        src: /home/ansibleadmin/jira/credentials.csv
        protocol: sftp
        dest: flash3:/tmp/jira/credentials.csv
