- name: tranferir archivo
  hosts: all
  become: yes
  tasks:
    # - name: Crear carpeta para instaladores
    #   file: path=/tmp/jira/jirasoftware state=directory
    ######################################################################
    # - name: Download file from a file path
    #   get_url:
    #     url: file:///home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/credentials.csv
    #   delegate_to: localhost
    #   ignore_errors: yes
    # - name: synchronize between nodes
    #   environment:
    #     RSYNC_PASSWORD: root
    #   synchronize:
    #     src: rsync://ansibleadmin@Ansible-Server:/home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/
    #     mode: pull
    #   delegate_to: localhost
    #   ignore_errors: yes
    # - name: Transfer file from ServerA to ServerB
    #   synchronize:
    #     src: /home/ansibleadmin/jira/credentials.csv
    #     dest: /tmp/jira/
    #   delegate_to: Ansible
    #   ignore_errors: yes
    #########################################################################
    # - name: Descomprimiendo archivo de instalacion
    #   unarchive:
    #     src: /tmp/jira/atlassian-jira-software-8.0.1.tar.gz
    #     dest: /tmp/jira/jirasoftware
    #     remote_src: yes
    # - name: Crea Usuario Jira
    #   command: useradd -d /home/jboss -s /bin/bash -m jira
    # - name: Crea Password Usuario Jira
    #   command: echo 1234 | passwd jira --stdin
    # - name: Usuario JBOSS Owner carpeta JBOSS
    #   command: chown -R jira /tmp/jira/jirasoftware
    # - name: Usuario JBOSS Owner carpeta JBOSS
    #   command: chmod -R u=rwx,go-rwx /tmp/jira/jirasoftware
    # - name: Crear carpeta para instaladores
    #   command: mkdir /home/jirasoftware-home
    # - name: Usuario JBOSS Owner carpeta Jira
    #   command: chown -R jira /home/jirasoftware-home
    # - name: Usuario JBOSS Owner carpeta Jira
    #   command: chmod -R u=rwx,go-rwx /home/jirasoftware-home
    # - name: Crea Variable JAVA
    #   shell: JIRA_HOME=/home/jirasoftware-home
    # - name: Export JIRA_HOME
    #   shell: export JIRA_HOME
    # - name: Start Jira
    #   become_user: jira
    #   become: yes
    #   shell: sh /tmp/jira/jirasoftware/atlassian-jira-software-8.0.1-standalone/bin/start-jira.sh
    #   environment:
    #     JIRA_HOME: /home/jirasoftware-home
    #     JAVA_HOME: /usr/java/jre-java
    #########################################################################
    - name: Dar permiso al Instalador Jira
      shell: chmod a+x atlassian-jira-software-8.0.1-x64.bin
    - name: Ejecutar Instalador de Jira
      shell: sh /tmp/atlassian-jira-software-8.0.1-x64.bin
