- name: Instalacion de Jira Software
  hosts: all
  become: yes
  tasks:
    # - name: Descargar bin y darle permiso de ejecución
    #   get_url:
    #     url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.0.2-x64.bin
    #     dest: /opt/
    #     mode: a+x
    - name: install ntpdate
      package:
        name: pip
        state: present
    - name: install pexpect
      pip:
        name: pexpect==3.3
    - name: Ejecutar archivo de Instalación
      expect:
        command: sh /opt/atlassian-jira-software-8.0.2-x64.bin
        responses:
          Question:
            - y
            - o
            - 1
            - y
            - y
      