- name: Instalacion de Jira Software
  hosts: all
  become: yes
  tasks:
    # - name: Descargar bin y darle permiso de ejecución
    #   get_url:
    #     url: https://www.atlassian.com/software/jira/downloads/binary/atlassian-jira-software-8.0.2-x64.bin
    #     dest: /opt/
    #     mode: a+x
    - name: Ejecutar archivo de Instalación
      shell: |
        sh /opt/atlassian-jira-software-8.0.2-x64.bin

        expect "Are you sure you want to continue?\nYes [y, Enter], No [n]"
        send "y\n"

        exit 0
      ignore_errors: true
    - name: Ejecutar archivo de Instalacio 2
      shell: echo y | sh /opt/atlassian-jira-software-8.0.2-x64.bin
        