- hosts: all
  tasks:
    - name: Crear carpeta para instaladores
      command: mkdir /tmp/jira
      ignore_errors: yes
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /home/ansibleadmin/jira/credentials.csv
        dest: /tmp/jira/credentials.csv
      delegate_to: localhost
