- hosts: all
  become: yes
  tasks:
    ################################ (Instalacion JAVA) ##################################
    - name: Crea Carpeta JAVA
      file: 
        path: /usr/java
        state: directory
    - name: Descomprime Archivo
      unarchive:
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: /usr/java
        remote_src: yes
    - name: Renombra carpeta java
      command: mv /usr/java/jdk1.8.0_201 /usr/java/jdk-java
    - name: Crea y exportar Variable JAVA
      shell: export JAVA_HOME=/usr/java/jdk-java
    - name: Crea y exporta Variable PATH
      shell: export PATH=$JAVA_HOME/bin:$PATH
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile-b-java.bkp
    - name: Agrega JAVA_HOME y PATH al archivo Profile
      shell: sed -i '$a JAVA_HOME=/usr/java/jdk-java' /etc/profile; sed -i '$a export JAVA_HOME' /etc/profile; sed -i '$a PATH=$JAVA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME=/usr/java/jdk-java"
        create: yes
    ################################ (Instalacion JIRA) ##################################
    - name: Crear carpeta para instaladores Jira
      file:
        path: /opt/jirasoftware
        state: directory
    - name: Crea Usuario Jira
      user:
        name: jira
        state: present
    - name: Remover Password Usuario Jira
      command: passwd -d jira
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /tmp/atlassian-jira-software-8.0.0.tar.gz
        dest: /opt/jirasoftware
        remote_src: yes
    - name: Permisos para carpeta de instaladores
      file:
        path: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /home/jirasoftware-home/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crea y exporta Variable JIRA_HOME
      shell: export JIRA_HOME=/home/jirasoftware-home
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile-b-jira.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: Agrega export JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export JIRA_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$JIRA_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    # - name: Copiar Archivo para Starting JIRA Automaticamente desde un hosts remoto
    - name: Copiar archivo para start de servicio jira
      copy:
        src: /tmp/jira
        dest: /etc/init.d/
        remote_src: yes
        mode: +x
    - name: Habilitar servicio jira
      shell: /sbin/chkconfig --add jira
      become: yes
    - name: selinux
      command: setenforce 0
    - name: firewall rhel7
      command: systemctl stop firewalld
    - name: systemctl 0
      lineinfile:
        path: /usr/lib/systemd/system/jira.service
        line: "[Unit]\n
              Description=JIRA Service\n
              After=network.target iptables.service firewalld.service firewalld.service httpd.service\n
              \n
              [Service]\n
              Type=forking\n
              User=jira\n
              Environment=JAVA_HOME=/usr/java/jdk-java\n
              Environment=JIRA_HOME=/home/jirasoftware-home\n
              ExecStart=/opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/start-jira.sh\n
              ExecStop=/opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin/stop-jira.sh\n
              \n
              [Install]\n
              \n
              WantedBy=multi-user.target"
        create: yes
    - name: systemctl 1
      become: yes
      shell: systemctl daemon-reload
    - name: systemctl 2
      become: yes
      shell: systemctl start jira
    