- hosts: all
  become: yes
  tasks:
    ################################ (Instalacion JAVA) ##################################
    - name: Crea Carpeta JAVA
      file: path=/usr/java state=directory
    - name: Descomprime Archivo
      unarchive:
        src: /tmp/jdk-8u201-linux-x64.tar.gz
        dest: /usr/java
        remote_src: yes
    - name: Renombra carpeta java
      command: mv /usr/java/jdk1.8.0_201 /usr/java/jdk-java
    - name: Crea y exportar Variable JAVA
      shell: export JAVA_HOME=/usr/java/jdk-java
    - name: Crea y exporta Variable PATH
      shell: export PATH=$JAVA_HOME/bin:$PATH
    - name: Respaldo Archivo Profile
      command: cp /etc/profile /etc/profile-b-java.bkp
    - name: Agrega JAVA_HOME y PATH al archivo Profile
      shell: sed -i '$a JAVA_HOME=/usr/java/jdk-java' /etc/profile; sed -i '$a export JAVA_HOME' /etc/profile; sed -i '$a PATH=$JAVA_HOME/bin:$PATH' /etc/profile; sed -i '$a export PATH' /etc/profile
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME=/usr/java/jdk-java"
        create: yes
    # - name: reboot
    #   reboot:
    #     reboot_timeout: 300
    - name: Crear carpeta para instaladores
      file:
        path: /opt/jirasoftware
        state: directory
    # - name: Tranferir archivo (tarea en desarrollo)
    - name: Crea Usuario Jira
      user:
        name: jira
        state: present
    - name: Remover Password Usuario Jira
      command: passwd -d jira
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /tmp/atlassian-jira-software-8.0.0.tar.gz
        dest: /opt/jirasoftware
        remote_src: yes
    - name: Permisos para carpeta de instaladores
      file:
        path: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /home/jirasoftware-home/
        state: directory
        owner: jira
        group: jira
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Crea y exporta Variable JIRA_HOME
      shell: export JIRA_HOME=/home/jirasoftware-home
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile-b-jira.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: Agrega export JIRA_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export JIRA_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$JIRA_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega JIRA_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "JIRA_HOME=/home/jirasoftware-home"
        create: yes
    - name: reboot
      reboot:
        reboot_timeout: 300
    # - name: Copiar Archivo para Starting JIRA Automaticamente desde un hosts remoto
    - name: Copiar archivo para start de servicio jira
      copy:
        dest: /etc/init.d/
        src: /tmp/jira
        remote_src: yes
        mode: +x
    - name: Habilitar servicio jira
      shell: /sbin/chkconfig --add jira
      become: yes
    - name: Start Jira
      become: yes
      become_user: jira
      become_method: su
      shell: service jira start
      environment:
        JIRA_HOME: /home/jirasoftware-home
        JAVA_HOME: /usr/java/jdk-java
        PATH: /opt/jirasoftware/atlassian-jira-software-8.0.0-standalone/bin:/home/jirasoftware-home/bin:/usr/java/jdk-java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
