- name: Crear carpeta de utilidades
  file: 
    path: /home/{{ ansible_ssh_user }}/performance/utils 
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copiar archivo para obtener ip de los esclavos
  copy:
    src: getSlavesIp.sh
    dest: /home/{{ ansible_ssh_user }}/performance/utils
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
