- name: Cambio de Password Instancia Openstack
  hosts: all
  become: yes
  task:
    - name: Cambiar PasswordAuthentication a yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        insertafter: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
    
    - name: Cambiar ssh_pwauth a 1
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ssh_pwauth'
        insertafter: "^ssh_pwauth:   0"
        line: "ssh_pwauth:   1"

    - name: Reload the sshd service
      command: service sshd reload
      
    - name: Crea Password Usuario linux
      command: echo linux | passwd linux --stdin
