- name: Cambio de Password Instancia Openstack 
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Esperando conección SSH
      wait_for_connection:
        delay: 15
        timeout: 120
    - name: Cambiar PasswordAuthentication a yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        insertafter: "^PasswordAuthentication no"
        line: "PasswordAuthentication yes"
    
    - name: Cambiar ssh_pwauth a 1
      lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: '^ssh_pwauth'
        insertafter: "^ssh_pwauth:   0"
        line: "ssh_pwauth:   1"

    - name: Reload the sshd service
      command: service sshd reload
      
    - name: Crea Password Usuario linux
      shell: "printf '{{ password }}\n{{ password }}\n' | passwd linux"