- name: Crear Instancia Openstack
  hosts: all
  tasks:
    - name: Create a new instance and attaches to a network and passes metadata to the instance
      os_server:
        state: present
        auth:
          auth_url: https://iam.sa-chile-1.telefonicaopencloud.com:443/v3
          project_name: sa-chile-1
          username: nebulatsoft
          project-domain-name: sa-chile-1
          user-domain-name: tsoft
          password: nebu@2019
        region_name: sa-chile-1
        interface: public
        name: "{{ vm_name }}"
        image: "{{ image_id }}"
        key_name: KeyPair-Nebula
        timeout: 300
        flavor: "{{ flavor }}"
        #auto_ip: yes
        network: 99500806-6aaa-451a-bbbd-05149fd179df
      # loop: "{{ vm_name_list }}"
      # loop_control:
      #   loop_var: "vm_name"
      
    - name: Creació y/o asignación de IP Elástica
      os_floating_ip:
        auth:
          auth_url: https://iam.sa-chile-1.telefonicaopencloud.com:443/v3
          project_name: sa-chile-1
          username: nebulatsoft
          project-domain-name: sa-chile-1
          user-domain-name: tsoft
          password: nebu@2019
        state: present
        server: "{{ vm_name }}"
        network: 99500806-6aaa-451a-bbbd-05149fd179df
        wait: true
        timeout: 225
        # loop: "{{ vm_name_list }}"
        # loop_control:
        #   loop_var: "vm_name" 