- name: Crear Instancia Openstack 
  hosts: all
  become: yes
  tasks:
    - name: mensaje en consola
      shell: wall $(date)
      async: 45
      poll: 0
      loop: "{{ durations }}"
      loop_control:
        loop_var: "async_item"
      register: async_results