########## Centos - Redhat #############
- name: upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Instalacion de Packetes y Pip
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - epel-release
    # - python-setuptools
    - python-pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
########## Ubuntu #############
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - epel-release
    - python-setuptools
    - python3-pip
  ignore_errors: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Descargar get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /root
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Instalando pip
  command: python /root/get-pip.py
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  ignore_errors: yes