########## Centos - Redhat #############
# - name: upgrade all packages
#   yum:
#     name: '*'
#     state: latest
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Instalacion de epel-release
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Instalacion de Pip
  yum:
    name: python-pip
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
########## Ubuntu #############
- apt:
    name: "{{ packages }}"
  vars:
    packages:
    - epel-release
    - python-setuptools
    - python3-pip
  ignore_errors: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'