- name: Instalacion de epel-release
  yum:
    name: epel-release
- yum:
    name: python-setuptools    
- name: instalar Python
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
- name: Instalando pip
  command: python get-pip.py