- name: Instalacion de OKD desde Template Azure
  hosts: all
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        resource_group: test-nebula
        auth_source: cli
        location: eastus
        #name: OKDNebula
        parameters:
          masterVmSize:
            value: Standard_D2s_v3
          infraVmSize:
            value: Standard_D2s_v3
          nodeVmSize:
            value: Standard_D2s_v3
          storageKind:
            value: managed
          openshiftClusterPrefix:
            value: nebuCluster
          masterInstanceCount:
            value: 1
          infraInstanceCount:
            value: 1
          nodeInstanceCount:
            value: 1
          dataDiskSize:
            value: 128
          adminUsername:
            value: tscloudform@outlook.com
          openshiftPassword:
            value: {20*tscf@18}
          sshPublicKey:
            value: {ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtPDM3e/qEqXMgBkqAH49G4V6otoarn4RJU0G+c9qufNpQ/cu+XVQz+pcnt5CRlMzCIpzjHMk1W4nHWTTgH+Ae94SFBnAL4034BCcnmat5CVWdOo+Xa+D3KoPZVVhpwIXk//yAxZ6rN/dfa02wDxbVuS/Ij4U07+3Gty3SJ01MHh381DtmfNBqXgY5jQICUE/jiKrrphzCxHpKgRyUZixQBFQJyPmU4hjAD8ua1vp8oI9XT//z6W9KDHW7KsdIeaBtStHpevar7XvvgYWjqJdbRX8y+dy4LAQlwI2tWKqCzgzLNiE/IsWew2Yb75tpWlxwWnKjw02GUGUwlexW415F ea1bad11-0580-4968-b16a-a699d7b4@cc-20b6f941-7fb556ddb7-v5x5s}
          # enableMetrics:
          #   value: true
          # enableLogging:
          #   value: true
          keyVaultResourceGroup:
            value: test-nebula
          keyVaultName:
            value: sercret-nebu-key
          keyVaultSecret:
            value: dslnfjdfhalfnasjlfnaslfnak{}
          enableAzure:
            value: true
          aadClientId:
            value: 5e3634e0-6d9c-40b6-b261-bfb64105ea68
          aadClientSecret:
            value: E.n5plSH9_]sBUH.0GMYyrwLwlVAY4]p
          defaultSubDomainType:
            value: custom
          defaultSubDomain:
            value: jhon.local
        template_link: https://raw.githubusercontent.com/Microsoft/openshift-origin/master/azuredeploy.json