- name: Instalacion de Docker
  hosts: all
  become: yes
  tasks:
    #### Ubuntu ####
    ################
    # ERROR --->>> Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)\n
    # ERROR --->>> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
    # - command: killall apt apt-get
    #   register: result
    #   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    #   ignore_errors: yes
      
    # - shell: rm /var/lib/apt/lists/lock; rm /var/cache/apt/archives/lock; rm /var/lib/dpkg/lock*
    #   register: result2
    #   when: result is failed
    #   ignore_errors: yes
    
    # - command: dpkg --configure -a
    #   register: result3
    #   when: result2 is succeeded
    #   ignore_errors: yes
    ################

    - name: Actualizar los paquetes a la última actualización
      apt:
        name: "*"
        state: latest
        force_apt_get: True
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Instalacion de packetes requeridos
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Agrega GPG Key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - name: Agregar repositorio 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ### Centos Redhat ###
    - name: Instalacion de packetes requeridos en Centos-Redhat
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when: ansible_facts['os_family'] == "RedHat"
    - name: Agregar repositorio Centos-Redhat
      shell: yum-config-manager \
            --add-repo \
            https://download.docker.com/linux/centos/docker-ce.repo
      # yum_repository:
      #   name: docker-ce
      #   description: Docker CE YUM repo
      #   baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"
    #### INSTALACION DE DOCKER ####
    - name: Instalación Docker CE
      package:
        name:  "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: User
      shell: usermod -aG docker $(whoami)
    ### HABILITANDO SERVICIO PARA REDHAT 7 ###
    - name: Enable Docker Service
      command: systemctl enable docker.service
      when: ansible_facts['os_family'] == "RedHat"and ansible_facts['distribution_major_version'] >= "7"
    - name: Start Docker
      command: systemctl start docker.service
      when: ansible_facts['os_family'] == "RedHat"and ansible_facts['distribution_major_version'] >= "7"