- name: Instalacion de Docker
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    #### Ubuntu ####
    - name: Esperando Coneccion SSH 2 min max
      wait_for_connection:
        delay: 15
        timeout: 180
    - name: Update all packages to the latest version
      register: result_apt
      until: result_apt.failed == false
      retries: 24
      delay: 15
      apt:
        update_cache: yes
      tags: apt
      when: ansible_facts['os_family'] == 'Debian'
    # - debug: var=result_apt
    - name: Instalacion de packetes requeridos
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      when: ansible_facts['os_family'] == 'Debian'
    - name: Agrega GPG Key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts['os_family'] == 'Debian'
    - name: Agregar repositorio 
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      when: ansible_facts['os_family'] == 'Debian'
    ### Centos Redhat ###
    - name: Update all packages to the latest version
      register: result_yum
      until: result_yum.failed == false
      retries: 24
      delay: 15
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'RedHat'
    - name: Instalacion de packetes requeridos en Centos-Redhat
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      when: ansible_facts['os_family'] == "RedHat"
    - name: Agregar repositorio Centos-Redhat
      shell: yum-config-manager \
            --add-repo \
            https://download.docker.com/linux/centos/docker-ce.repo
      # yum_repository:
      #   name: docker-ce
      #   description: Docker CE YUM repo
      #   baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"
    #### INSTALACION DE DOCKER ####
    - name: Instalación Docker CE
      register: result
      package:
        name:  "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      until: result.failed == false
      retries: 30
      delay: 15
    #- debug: var=result2
    - name: User
      shell: usermod -aG docker $(whoami)
    ### HABILITANDO SERVICIO ###
    - name: Enable Docker Service
      service: 
        name: docker.service
        enabled: yes
    - name: Start Docker
      service: 
        name: docker.service
        state: started 