- name: Instalación GoLang
  hosts: all
  become: yes
  vars:
    version_golang: 1.12.4
  tasks:
  - name: Descargar archivo 
    get_url:
      url: https://dl.google.com/go/go{{ version_golang }}.linux-amd64.tar.gz
      dest: /tmp
  - name: Descomprime archivo
    unarchive:
      src: /tmp/go{{ version_golang }}.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: Export GOROOT
    shell: export GOROOT=/usr/local/go/bin
  - name: Export PATH
    shell: export PATH=$PATH:$GOROOT
  - shell: source /etc/profile
  - name: Agrega GOROOT al anchivo Environment
    lineinfile:
      path: /etc/environment
      line: GOROOT=/usr/local/go/bin
      create: yes
  