- name: Instalación GoLang
  hosts: all
  become: yes
  vars:
    version_golang: 1.12.4
  tasks:
  - name: Descargar archivo 
    get_url:
      url: https://dl.google.com/go/go{{ version_golang }}.linux-amd64.tar.gz
      dest: /tmp
  - name: Descomprime archivo
    unarchive:
      src: /tmp/go{{ version_golang }}.linux-amd64.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: Export GOROOT
    command: export GOROOT=/usr/local/go/bin
  - name: Export PATH
    command: export PATH=$PATH:$GOROOT
  - command: source ~/.bash_profile
  