- name: Plantilla para correr Contenedores docker con imagenes de Doker Hub
  hosts: all
  roles:
    - app/docker-install
  tasks:
    - name: Creando contenedor desde Docker Hub
      command: docker run --name {{ containerName }} -d -p {{ portIn }}:{{ portOut }} {{ imageOwner }}/{{ imageName }}:{{imageTag}}