- name: Instalación Proyecto de Jasmine + Karma 
  hosts: all
  become: yes
  roles:
    - app/golang-install
    - app/docker-install
  tasks:
  - name: Actualizar los paquetes a la última actualización
    apt:
      name: "*"
      state: latest
      force_apt_get: True
    when: ansible_facts['os_family'] == "Debian"
  - name: Instalacion de packetes requeridos
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - apt-transport-https
    when: ansible_facts['os_family'] == "Debian"
  - name: Agrega GPG Key
    apt_key: 
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    when: ansible_facts['os_family'] == "Debian"
  - name: Agregar repositorio 
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    when: ansible_facts['os_family'] == "Debian"
    
  - name: Instalación de Kubernetes
    command: "echo 'deb https://apt.kubernetes.io/ kubernetes-xenial main' | sudo tee -a /etc/apt/sources.list.d/kubernetes.list"
    when: ansible_facts['os_family'] == "Debian"
  - name: Actualizar los paquetes a la última actualización
    apt:
      name: "*"
      state: latest
      force_apt_get: True
    when: ansible_facts['os_family'] == "Debian"
  - name: Instalación de Kubernetes
    apt:
      name: kubectl
      state: present
    when: ansible_facts['os_family'] == "Debian"
  - name: Añadiendo repositorio de Kubernetes
    lineinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      line: "[kubernetes]\nname=Kubernetes\nbaseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg\nEOF"
      create: yes
    when: ansible_facts['os_family'] == "RedHat"
  - name: Instalación de packetes requeridos en Centos-Redhat
    yum:
      name: kubectl
      state: present
    when: ansible_facts['os_family'] == "RedHat"
  - name: Instalando entorno
    shell: go get -u sigs.k8s.io/kind && kind create cluster