- name: Instalacion de NodeJS + NPM
  hosts: all
  become: yes
  tasks:
    - name: Instalacion de epel-release
      yum:
        name: epel-release
    - yum:
        name: python-setuptools    
    - name: Descargar get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /root
    - name: Instalando pip
      command: python get-pip.py