- name: Instalación Proyecto de Jasmine + Karma 
  hosts: all
  become: yes
  roles:
    - app/nodejs-install
    - app/npm-install
  tasks:
  - name: Instalación de TypeScript
    npm:
      name: "protractor"
      global: yes
  - name: actualizando y start de protractor
    shell: webdriver-manager update; webdriver-manager start
    async: 20
    poll: 0
