- name: Instalación Proyecto de Kubernetes
  hosts: all
  become: yes
  roles:
    - app/java-install
    - db/postgresql-install
    - firewall-turnoff
  tasks:
  - name: Paquetes requeridos
    package:
      name: ntpdate
      state: present
  - name: Descomprimiendo archivo zip
    unarchive:
      src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.7.zip
      dest: /usr/local
      remote_src: yes
  #- command: ALTER USER mySonarUser SET search_path to mySonarQubeSchema
  - name: Export SONARQUBE_HOME
    shell: export SONARQUBE_HOME=/usr/local/sonarqube-7.7/bin
  - name: Export PATH
    shell: export PATH=$PATH:$SONARQUBE_HOME
  - shell: source /etc/profile
  - name: Agrega SONARQUBE_HOME al anchivo Environment
    lineinfile:
      path: /etc/environment
      line: SONARQUBE_HOME=/usr/local/sonarqube-7.7/bin
      create: yes
  - name: Habilitando postgresql en archivo de conf
    lineinfile:
      path: /usr/local/sonarqube-7.7/conf/sonar.properties
      regexp: '^#sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube?currentSchema=my_schema'
      line: "sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube"
      create: yes

  - name: Agregando usuario y pass de la db al archivo de conf
    lineinfile:
      path: /usr/local/sonarqube-7.7/conf/sonar.properties
      regexp: "^#sonar.jdbc.username=\n#sonar.jdbc.password=\n"
      line: "sonar.jdbc.username=sonarqube\nsonar.jdbc.password=mypassword\n"
      create: yes
  