- name: Instalación Proyecto de Kubernetes
  hosts: all
  become: yes
  # roles:
  #   - app/java-install
  #   - app/python-install
  #   - app/python-pip-install
  #   - db/postgresql-install
  #   - firewall-turnoff
  tasks:
  ### Configuraciones de Base de Datos
  # - name: Modificacion de anchivo pg_hba.conf
  #   lineinfile:
  #     path: /var/lib/pgsql/data/pg_hba.conf
  #     regexp: '^local   all             all                                     peer'
  #     line: "local   all             all                                     trust"
  #     owner: root
  #     group: root
  # - name: Modificacion de anchivo pg_hba.conf
  #   lineinfile:
  #     path: /var/lib/pgsql/data/pg_hba.conf
  #     regexp: '^host    all             all             127.0.0.1/32            ident'
  #     line: "host    all             all             127.0.0.1/32            md5"
  #     owner: root
  #     group: root
  # - name: Modificacion de anchivo pg_hba.conf
  #   lineinfile:
  #     path: /var/lib/pgsql/data/pg_hba.conf
  #     regexp: '^host    all             all             ::1/128                 ident'
  #     line: "host    all             all             ::1/128                 md5"
  #     owner: root
  #     group: root
  # - name: Creando usuario postgres para SonrQube
  #   postgresql_user:
  #     name: sonar
  #     password: sonar*2019
  # - name: Creacion de Base de datos para SonaQube
  #   postgresql_db:
  #     name: sonar
  #     owner: sonar

  ### Instalando SonarQube
  # - name: Paquete requerido
  #   package:
  #     name: epel-release
  #     state: present
  # - name: Obteniendo y descomprimiendo archivo zip
  #   unarchive:
  #     src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.7.zip
  #     dest: /usr/local
  #     remote_src: yes
  - name: Export SONARQUBE_HOME
    shell: export SONARQUBE_HOME=/usr/local/sonarqube-7.7/bin
  - name: Export PATH
    shell: export PATH=$PATH:$SONARQUBE_HOME
  - shell: source /etc/profile
  - name: Agrega SONARQUBE_HOME al anchivo Environment
    lineinfile:
      path: /etc/environment
      line: SONARQUBE_HOME=/usr/local/sonarqube-7.7/bin
      create: yes
  - name: Habilitando postgresql en archivo de conf
    lineinfile:
      path: /usr/local/sonarqube-7.7/conf/sonar.properties
      regexp: '^#sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube?currentSchema=my_schema'
      line: "sonar.jdbc.url=jdbc:postgresql://{{ ansible_ssh_host }}/sonarqube"
  - name: Agregando usuario y pass de la db al archivo de conf
    lineinfile:
      path: /usr/local/sonarqube-7.7/conf/sonar.properties
      regexp: "^#sonar.jdbc.username=
      #sonar.jdbc.password="
      line: "sonar.jdbc.username=sonar\nsonar.jdbc.password=sonar*2019\n"
      
  # - name: Configurando host servidor web {{ ansible_ssh_host }}
  #   lineinfile:
  #     path: /usr/local/sonarqube-7.7/conf/sonar.properties
  #     regexp: "^#sonar.web.host=0.0.0.0"
  #     line: "sonar.web.host={{ ansible_ssh_host }}"
  #     create: yes

  # - name: Configurando port servidor web
  #   lineinfile:
  #     path: /usr/local/sonarqube-7.7/conf/sonar.properties
  #     regexp: "^#sonar.port=9000"
  #     line: "sonar.web.port=80"
  #     create: yes

  # - name: Configurando port servidor web
  #   lineinfile:
  #     path: /usr/local/sonarqube-7.7/conf/sonar.properties
  #     regexp: "^#sonar.context="
  #     line: "sonar.web.context=/sonarqube"
  #     create: yes