- name: Instalacion de Bamboo
  hosts: all
  become: yes
  roles:
    - app/java-install
    - firewall-turnoff
  tasks:
    ######### Instalación Bamboo ############
    - name: Crea Usuario Bamboo
      user:
        name: bamboo
        state: present
    - name: Remover Password Usuario Bamboo
      command: passwd -d bamboo
    - name: Descargar bin y darle permiso de ejecución
      get_url:
        url: https://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-6.8.1.tar.gz
        dest: /tmp/
        mode: a+x
      ignore_errors: yes
    - name: Crear carpeta y permisos para instaladores
      file:
        path: /opt/atlassian/bamboo/
        state: directory
        owner: bamboo
        group: bamboo
        mode: u=rwx,go-rwx
        recurse: yes
    - name: Descomprimiendo archivo de instalacion
      unarchive:
        src: /tmp/atlassian-bamboo-6.8.1.tar.gz
        dest: /opt/atlassian/bamboo/
        owner: bamboo
        group: bamboo
        mode: u=rwx,go-rwx
        remote_src: yes
    - name:  comando ln
      shell: ln -s atlassian-bamboo-5.14.3.1 current
    - name: Agrega bamboo.home a bamboo-init.properties
      lineinfile:
        path: /opt/atlassian/bamboo/atlassian-bamboo-6.8.1/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties
        line: "bamboo.home=/home/bamboo"
        create: yes

    - name: Crea y exporta Variable BAMBOO_HOME
      shell: export BAMBOO_HOME=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/
    - name: Respaldo Archivo Profile
      copy:
        src: /etc/profile
        dest: /etc/profile.bkp
        remote_src: yes
        mode: 0664
    - name: Agrega BAMBOO_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "BAMBOO_HOME=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/"
        create: yes
    - name: Agrega export BAMBOO_HOME al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export BAMBOO_HOME"
        create: yes
    - name: Agrega PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "PATH=$BAMBOO_HOME/bin:$PATH"
        create: yes
    - name: Agrega export PATH al archivo Profile
      lineinfile:
        path: /etc/profile
        line: "export PATH"
        create: yes
    - name: Source Archivo Profile
      shell: source /etc/profile
    - name: Agrega BAMBOO_HOME al anchivo Environment
      lineinfile:
        path: /etc/environment
        line: "BAMBOO_HOME=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/"
        create: yes

    # - name: servicio con systemctl
    #   lineinfile:
    #     path: /etc/systemd/system/bamboo.service
    #     line: "[Unit]\n
    #           Description=Atlassian Bamboo\n
    #           After=syslog.target network.target\n
    #           \n
    #           [Service]\n
    #           Type=forking\n
    #           User=bamboo\n
    #           ExecStart=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/bin/start-bamboo.sh\n
    #           ExecStop=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/bin/stop-bamboo.sh\n
    #           SuccessExitStatus=143\n
    #           \n
    #           [Install]\n
    #           WantedBy=multi-user.target"
    #     create: yes
    # - name: Enable Bamboo
    #   command: systemctl enable bamboo.service
    # - name: Start Bamboo
    #   command: systemctl start bamboo
    
    - name: Archivo Service
      lineinfile:
        path: /etc/init.d/bamboo.service
        line: "#!/bin/sh -e\n
              # bamboo startup script\n
              #chkconfig: 2345 80 05\n
              #description: bamboo\n
              \n
              # Define some variables\n
              # Name of app ( bamboo, Confluence, etc )\n
              APP=bamboo\n
              # Name of the user to run as\n
              USER=bamboo\n
              # Location of application's bin directory\n
              BASE=/opt/atlassian/bamboo/atlassian-bamboo-6.8.1/\n
              # Location of Java JDK\n
              export JAVA_HOME=/usr/java/jdk-java/\n
              export HOME=/home/bamboo\n
              \n
              case \"$1\" in \n
              # Start command\n
              start)\n
                echo \"Starting $APP\"\n
                /bin/su -m $USER -c \"cd $BASE/logs && $BASE/bin/startup.sh &> /dev/null\"\n
                ;;\n
              # Stop command\n
              stop)\n
                echo \"Stopping $APP\"\n
                /bin/su -m $USER -c \"$BASE/bin/shutdown.sh &> /dev/null\"\n
                echo \"$APP stopped successfully\"\n
                ;;\n
                # Restart command\n
                restart)\n
                    $0 stop\n
                    sleep 5\n
                    $0 start\n
                    ;;\n
              *)\n
                echo \"Usage: /etc/init.d/$APP {start|restart|stop}\"\n
                exit 1\n
                ;;\n
              esac\n
              \n
              exit 0"
        create: yes
        mode: u=rwx,g=x,o=r 
    - name: Start Bamboo
      shell: service bamboo.service start